name: ${project.name}
version: ${project.version}
description: ${project.description}
website: ${project.url}
main: blainicus.MonsterApocalypse.MonsterApocalypse

softdepend:
    - Multiverse-Core
    - WorldGuard
    - CreeperHeal
    - MobAPA

commands:
   monsterapocalypse:
      description: Handler for all Monster Apocalypse commands.
      aliases: [ma, mobapocalypse, monsterapoc, mobapoc, mapocalypse, mapoc, monstera, moba]
      permission: Monster Apocalypse.spawnpoints
      usage: /ma (Monster Apocalypse Spawnpoint Command) [name] args...